package HttpRocket_Git;

import javax.swing.*;
import java.awt.*;
import java.net.*;
import java.io.*;

public class AuthorWindow extends javax.swing.JFrame {

    public AuthorWindow() {
        initComponents();
        this.setSize(300, 240);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(AuthorWindow.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Credits1 = new javax.swing.JLabel();
        Credits2 = new javax.swing.JLabel();
        Credits3 = new javax.swing.JLabel();
        Credits5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 240));
        setResizable(false);

        Credits1.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        Credits1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Credits1.setText("Credits");
        Credits1.setMaximumSize(new java.awt.Dimension(85, 30));
        Credits1.setMinimumSize(new java.awt.Dimension(85, 30));
        Credits1.setOpaque(true);
        Credits1.setPreferredSize(new java.awt.Dimension(85, 30));

        Credits2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        Credits2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Credits2.setText("CopyRight 2017");
        Credits2.setMaximumSize(new java.awt.Dimension(106, 20));
        Credits2.setMinimumSize(new java.awt.Dimension(106, 20));
        Credits2.setPreferredSize(new java.awt.Dimension(106, 20));

        Credits3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        Credits3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Credits3.setText("Made By");
        Credits3.setMaximumSize(new java.awt.Dimension(49, 20));
        Credits3.setMinimumSize(new java.awt.Dimension(49, 20));
        Credits3.setName(""); // NOI18N
        Credits3.setPreferredSize(new java.awt.Dimension(49, 20));

        Credits5.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        Credits5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Credits5.setText("tic.toc.developer@icloud.com");
        Credits5.setMaximumSize(new java.awt.Dimension(147, 20));
        Credits5.setMinimumSize(new java.awt.Dimension(147, 20));
        Credits5.setPreferredSize(new java.awt.Dimension(147, 20));
        Credits5.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Credits1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Credits5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Credits2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Credits3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Credits1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Credits2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Credits3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Credits5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Credits1;
    private javax.swing.JLabel Credits2;
    private javax.swing.JLabel Credits3;
    private javax.swing.JLabel Credits5;
    // End of variables declaration//GEN-END:variables
}
