package HttpRocket_Git;

import java.util.Vector;
import javax.swing.*;
//import javax.swing.JOptionPane;
//import javax.swing.JTextField;

public class KeywordWindow extends javax.swing.JFrame {

    /**
     * Creates new form KeywordWindow
     */
    private Vector<String> key_list;
    private JTextField KeywordField;

    public KeywordWindow(JTextField KeywordField, Vector<String> key_list) {
        initComponents();
        this.setSize(425, 300);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(KeywordWindow.DISPOSE_ON_CLOSE);
        this.key_list = key_list;
        this.KeywordField = KeywordField;
        init();
    }

    private void init() {
        ListDisplay.setListData(key_list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KeywordScrollDisplay = new javax.swing.JScrollPane();
        ListDisplay = new javax.swing.JList<>();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(425, 300));
        setResizable(false);

        KeywordScrollDisplay.setViewportView(ListDisplay);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KeywordScrollDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(AddButton)
                .addGap(18, 18, 18)
                .addComponent(DeleteButton)
                .addGap(18, 18, 18)
                .addComponent(ConfirmButton)
                .addGap(18, 18, 18)
                .addComponent(CancelButton)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KeywordScrollDisplay)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // cancel
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // add  
        String addStr = JOptionPane.showInputDialog("Please input the keyword");
        if (!addStr.equals("")) {
            key_list.add(addStr);
        }
        ListDisplay.setListData(key_list);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // delete
        if (ListDisplay.getSelectedValues().length > 0) {
            Object[] objArr = ListDisplay.getSelectedValues();
            for (int i = 0; i < objArr.length; i++) {
                key_list.remove(objArr[i]);
            }
            ListDisplay.setListData(key_list);
            // vectorList = null;
            // vectorList = new JList(v);
        } else {
            JOptionPane.showMessageDialog(null, "At least choose one");
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // confirm
        String keys = "";
        for (int i = 0; i < key_list.size(); i++) {
            keys += key_list.get(i) + ";";
        }

        KeywordField.setText(keys);
        dispose();
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JScrollPane KeywordScrollDisplay;
    private javax.swing.JList<String> ListDisplay;
    // End of variables declaration//GEN-END:variables
}
